2018-12-15T06:20:35.292Z error: 	db-util.js:::initDB:::some error occurred while connecting to db => MongoNetworkError: failed to connect to server [localhost:2701] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:2701]
    at Pool.<anonymous> (/home/peps/misc/GetMapped/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/home/peps/misc/GetMapped/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/home/peps/misc/GetMapped/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
2018-12-23T08:08:22.910Z error: 	db-util.js:::getFromDB:::Inside Catch block => TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.validate (/home/peps/misc/GetMapped/util/verify-util.js:23:89)
    at /home/peps/misc/GetMapped/util/db-util.js:75:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
2018-12-23T08:08:22.912Z error: 	routes.js:::/:::Error thrown to the endpointundefined::Converting circular structure to JSON => TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.validate (/home/peps/misc/GetMapped/util/verify-util.js:23:89)
    at /home/peps/misc/GetMapped/util/db-util.js:75:24
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
